#include "adapters/F1_24/DataConversionMaps.h"

#include <map>
#include "data/internal/Session.h"
#include "data/game/F1_24/Session.h"
#include "data/game/F1_24/Participant.h"



const std::map<Session::Game::F1_24::Track, Session::Internal::Track>
NetCom::Adapter::F1_24::DataConversionMaps::TRACK_ID_MAP = {
    { Session::Game::F1_24::Track::InvalidUnknown           , Session::Internal::Track::Unknown },
    { Session::Game::F1_24::Track::AUS_Melbourne            , Session::Internal::Track::AUS_Melbourne },
    { Session::Game::F1_24::Track::FRA_PaulRicard           , Session::Internal::Track::FRA_PaulRicard },
    { Session::Game::F1_24::Track::CHI_Shanghai             , Session::Internal::Track::CHI_Shanghai },
    { Session::Game::F1_24::Track::BAH_Sakhir               , Session::Internal::Track::BAH_Sakhir },
    { Session::Game::F1_24::Track::SPA_Catalunya            , Session::Internal::Track::SPA_Catalunya },
    { Session::Game::F1_24::Track::MON_Monaco               , Session::Internal::Track::MON_Monaco },
    { Session::Game::F1_24::Track::CAN_Montreal             , Session::Internal::Track::CAN_Montreal },
    { Session::Game::F1_24::Track::ENG_Silverstone          , Session::Internal::Track::ENG_Silverstone },
    { Session::Game::F1_24::Track::GER_Hockenheim           , Session::Internal::Track::Unknown },
    { Session::Game::F1_24::Track::HUN_Hungaroring          , Session::Internal::Track::HUN_Hungaroring },
    { Session::Game::F1_24::Track::BEL_Spa                  , Session::Internal::Track::BEL_Spa },
    { Session::Game::F1_24::Track::ITA_Monza                , Session::Internal::Track::ITA_Monza },
    { Session::Game::F1_24::Track::SNG_Singapore            , Session::Internal::Track::SNG_Singapore },
    { Session::Game::F1_24::Track::JAP_Suzuka               , Session::Internal::Track::JAP_Suzuka },
    { Session::Game::F1_24::Track::UAE_AbuDhabi             , Session::Internal::Track::UAE_AbuDhabi },
    { Session::Game::F1_24::Track::USA_Texas                , Session::Internal::Track::USA_Texas },
    { Session::Game::F1_24::Track::BRA_Interlagos           , Session::Internal::Track::BRA_Interlagos },
    { Session::Game::F1_24::Track::AUT_RedBullRing          , Session::Internal::Track::AUT_RedBullRing },
    { Session::Game::F1_24::Track::RUS_Sochi                , Session::Internal::Track::Unknown },
    { Session::Game::F1_24::Track::MEX_MexicoCity           , Session::Internal::Track::MEX_MexicoCity },
    { Session::Game::F1_24::Track::AZE_Baku                 , Session::Internal::Track::AZE_Baku },
    { Session::Game::F1_24::Track::BAH_SakhirShort          , Session::Internal::Track::Unknown },
    { Session::Game::F1_24::Track::ENG_SilverstoneShort     , Session::Internal::Track::Unknown },
    { Session::Game::F1_24::Track::USA_TexasShort           , Session::Internal::Track::Unknown },
    { Session::Game::F1_24::Track::JAP_SuzukaShort          , Session::Internal::Track::Unknown },
    { Session::Game::F1_24::Track::VIE_Hanoi                , Session::Internal::Track::Unknown },
    { Session::Game::F1_24::Track::NED_Zandvoort            , Session::Internal::Track::NED_Zandvoort },
    { Session::Game::F1_24::Track::ITA_Imola                , Session::Internal::Track::ITA_Imola },
    { Session::Game::F1_24::Track::POR_Portimao             , Session::Internal::Track::POR_Portimao },
    { Session::Game::F1_24::Track::SAU_Jeddah               , Session::Internal::Track::SAU_Jeddah },
    { Session::Game::F1_24::Track::USA_Miami                , Session::Internal::Track::USA_Miami },
    { Session::Game::F1_24::Track::USA_LasVegas             , Session::Internal::Track::USA_LasVegas },
    { Session::Game::F1_24::Track::QAT_Losail               , Session::Internal::Track::QAT_Losail },
};



const std::map<Participant::Game::F1_24::TeamID, Session::Internal::TeamID>
NetCom::Adapter::F1_24::DataConversionMaps::TEAM_ID_MAP = {
    { Participant::Game::F1_24::TeamID::Mercedes        , Session::Internal::TeamID::Mercedes },
    { Participant::Game::F1_24::TeamID::Ferrari         , Session::Internal::TeamID::Ferrari },
    { Participant::Game::F1_24::TeamID::RedBull         , Session::Internal::TeamID::RedBull },
    { Participant::Game::F1_24::TeamID::Williams        , Session::Internal::TeamID::Williams },
    { Participant::Game::F1_24::TeamID::AstonMartin     , Session::Internal::TeamID::AstonMartin },
    { Participant::Game::F1_24::TeamID::Alpine          , Session::Internal::TeamID::Alpine },
    { Participant::Game::F1_24::TeamID::VCARB      , Session::Internal::TeamID::VCARB },
    { Participant::Game::F1_24::TeamID::Haas            , Session::Internal::TeamID::Haas },
    { Participant::Game::F1_24::TeamID::McLaren         , Session::Internal::TeamID::McLaren },
    { Participant::Game::F1_24::TeamID::KickSauber       , Session::Internal::TeamID::KickSauber },
    { Participant::Game::F1_24::TeamID::F1CustomTeam        , Session::Internal::TeamID::Custom },
    { Participant::Game::F1_24::TeamID::Prema2023           , Session::Internal::TeamID::Prema },
    { Participant::Game::F1_24::TeamID::Virtuosi2023        , Session::Internal::TeamID::Virtuosi },
    { Participant::Game::F1_24::TeamID::Carlin2023          , Session::Internal::TeamID::Carlin },
    { Participant::Game::F1_24::TeamID::MPMotorsport2023    , Session::Internal::TeamID::MPMotorsport },
    { Participant::Game::F1_24::TeamID::Dams2023            , Session::Internal::TeamID::Dams },
    { Participant::Game::F1_24::TeamID::Campos2023          , Session::Internal::TeamID::Campos },
    { Participant::Game::F1_24::TeamID::VanAmersfoort2023   , Session::Internal::TeamID::VanAmersfoort },
    { Participant::Game::F1_24::TeamID::Trident2023         , Session::Internal::TeamID::Trident },
    { Participant::Game::F1_24::TeamID::Hitech2023          , Session::Internal::TeamID::Hitech },
    { Participant::Game::F1_24::TeamID::Art2023             , Session::Internal::TeamID::Art },
    { Participant::Game::F1_24::TeamID::PHM2023             , Session::Internal::TeamID::PHM }

};



const std::map<Participant::Game::F1_24::DriverID, const char*>
NetCom::Adapter::F1_24::DataConversionMaps::DRIVER_SHORTHAND_MAP = {
    { Participant::Game::F1_24::DriverID::NetworkHuman              , "" },     // Deliberately empty
    { Participant::Game::F1_24::DriverID::CarlosSainz               , "SAI" },
    { Participant::Game::F1_24::DriverID::DaniilKvyat               , "KVY" },
    { Participant::Game::F1_24::DriverID::DanielRicciardo           , "RIC" },
    { Participant::Game::F1_24::DriverID::FernandoAlonso            , "ALO" },
    { Participant::Game::F1_24::DriverID::FelipeMassa               , "MAS" },
    { Participant::Game::F1_24::DriverID::KimiRaikkonen             , "RAI" },
    { Participant::Game::F1_24::DriverID::LewisHamilton             , "HAM" },
    { Participant::Game::F1_24::DriverID::MaxVerstappen             , "VER" },
    { Participant::Game::F1_24::DriverID::NicoHulkenburg            , "HUL" },
    { Participant::Game::F1_24::DriverID::KevinMagnussen            , "MAG" },
    { Participant::Game::F1_24::DriverID::RomainGrosjean            , "GRO" },
    { Participant::Game::F1_24::DriverID::SebastianVettel           , "VET" },
    { Participant::Game::F1_24::DriverID::SergioPerez               , "PER" },
    { Participant::Game::F1_24::DriverID::ValtteriBottas            , "BOT" },
    { Participant::Game::F1_24::DriverID::EstebanOcon               , "OCO" },
    { Participant::Game::F1_24::DriverID::LanceStroll               , "STR" },
    { Participant::Game::F1_24::DriverID::NyckDeVries               , "NDV" },
    { Participant::Game::F1_24::DriverID::JackAitken                , "AIT" },
    { Participant::Game::F1_24::DriverID::GeorgeRussell             , "RUS" },
    { Participant::Game::F1_24::DriverID::LandoNorris               , "NOR" },
    { Participant::Game::F1_24::DriverID::CharlesLeclerc            , "LEC" },
    { Participant::Game::F1_24::DriverID::PierreGasly               , "GAS" },
    { Participant::Game::F1_24::DriverID::AlexanderAlbon            , "ALB" },
    { Participant::Game::F1_24::DriverID::NicholasLatifi            , "LAT" },
    { Participant::Game::F1_24::DriverID::DevonButler               , "BUT" },
    { Participant::Game::F1_24::DriverID::AntonioGiovinazzi         , "GIO" },
    { Participant::Game::F1_24::DriverID::RobertKubica              , "KUB" },
    { Participant::Game::F1_24::DriverID::AlainProst                , "PRO" },
    { Participant::Game::F1_24::DriverID::AyrtonSenna               , "SEB" },
    { Participant::Game::F1_24::DriverID::NobuharuMatsushita        , "MAT" },
    { Participant::Game::F1_24::DriverID::NikitaMazepin             , "MAZ" },
    { Participant::Game::F1_24::DriverID::GuanyaZhou                , "ZHO" },
    { Participant::Game::F1_24::DriverID::MickSchumacher            , "MSC" },
    { Participant::Game::F1_24::DriverID::JuanManuelCorrea          , "COR" },
    { Participant::Game::F1_24::DriverID::MahaveerRaghunathan       , "RAG" },
    { Participant::Game::F1_24::DriverID::TatianaCalderon           , "CAL" },
    { Participant::Game::F1_24::DriverID::AnthoineHubert            , "HUB" },
    { Participant::Game::F1_24::DriverID::GuilianoAlesi             , "GAL" },
    { Participant::Game::F1_24::DriverID::RalphBoschung             , "BOS" },
    { Participant::Game::F1_24::DriverID::MichaelSchumacher         , "MSC" },
    { Participant::Game::F1_24::DriverID::DanTicktum                , "TIC" },
    { Participant::Game::F1_24::DriverID::MarcusArmstrong           , "ARM" },
    { Participant::Game::F1_24::DriverID::ChristianLundgaard        , "LND" },
    { Participant::Game::F1_24::DriverID::YukiTsunoda               , "TSU" },
    { Participant::Game::F1_24::DriverID::JehanDaruvala             , "DAR" },
    { Participant::Game::F1_24::DriverID::PedroPiquet               , "PPQ" },
    { Participant::Game::F1_24::DriverID::FelipeDrugovich           , "DRU" },
    { Participant::Game::F1_24::DriverID::RobertSchwartzman         , "SCW" },
    { Participant::Game::F1_24::DriverID::RoyNissany                , "NIS" },
    { Participant::Game::F1_24::DriverID::MarinoSato                , "SAT" },
    { Participant::Game::F1_24::DriverID::JensonButton              , "BUT" },
    { Participant::Game::F1_24::DriverID::DavidCoulthard            , "COU" },
    { Participant::Game::F1_24::DriverID::NicoRosberg               , "ROS" },
    { Participant::Game::F1_24::DriverID::OscarPiastri              , "PIA" },
    { Participant::Game::F1_24::DriverID::LiamLawson                , "LAW" },
    { Participant::Game::F1_24::DriverID::JuriVips                  , "VIP" },
    { Participant::Game::F1_24::DriverID::TheoPourchaire            , "TPO" },
    { Participant::Game::F1_24::DriverID::RichardVerschoor          , "RVS" },
    { Participant::Game::F1_24::DriverID::BentViscaal               , "VIS" },
    { Participant::Game::F1_24::DriverID::EnzoFittipaldi            , "FIT" },
    { Participant::Game::F1_24::DriverID::MarkWebber                , "WEB" },
    { Participant::Game::F1_24::DriverID::JacquesVilleneuve         , "JVI" },
    { Participant::Game::F1_24::DriverID::FrederikVesti             , "VES" },
    { Participant::Game::F1_24::DriverID::LoganSargeant             , "SAR" },
    { Participant::Game::F1_24::DriverID::AyumuIwasa                , "IWA" },
    { Participant::Game::F1_24::DriverID::ClementNovalak            , "NOV" },
    { Participant::Game::F1_24::DriverID::JackDoohan                , "DOO" },
    { Participant::Game::F1_24::DriverID::AmauryCordeel             , "COR" },
    { Participant::Game::F1_24::DriverID::DennisHauger              , "HAU" },
    { Participant::Game::F1_24::DriverID::CalanWilliams             , "CWI" },
    { Participant::Game::F1_24::DriverID::JamieChadwick             , "CHA" },
    { Participant::Game::F1_24::DriverID::KamuiKobayashi            , "KOB" },
    { Participant::Game::F1_24::DriverID::PastorMaldonado           , "MAL" },
    { Participant::Game::F1_24::DriverID::MikaHakkinen              , "HAK" },
    { Participant::Game::F1_24::DriverID::NigelMansell              , "MAN" },
    { Participant::Game::F1_24::DriverID::ZaneMaloney               , "MAL" },
    { Participant::Game::F1_24::DriverID::VictorMartins             , "VMA" },
    { Participant::Game::F1_24::DriverID::OliverBearman             , "BEA" },
    { Participant::Game::F1_24::DriverID::JakCrawford               , "JCA" },
    { Participant::Game::F1_24::DriverID::IsackHadjar               , "HAD" },
    { Participant::Game::F1_24::DriverID::ArthurLeclerc             , "ALC" },
    { Participant::Game::F1_24::DriverID::BradBenavides             , "BEN" },
    { Participant::Game::F1_24::DriverID::RomanStanek               , "STA" },
    { Participant::Game::F1_24::DriverID::KushMaini                 , "MAI" },
    { Participant::Game::F1_24::DriverID::JamesHunt                 , "JHU" },
    { Participant::Game::F1_24::DriverID::JPMontoya                 , "MON" },
    { Participant::Game::F1_24::DriverID::BrendonLeigh              , "LEI" },
    { Participant::Game::F1_24::DriverID::DavidTonizza              , "TON" },
    { Participant::Game::F1_24::DriverID::JarnoOpmeer               , "OPM" },
    { Participant::Game::F1_24::DriverID::LucasBlakeley             , "LBL" }
};